version: "3.8"
services:
  ingestion_service:
    container_name: ingestion_service
    env_file: .env
    ports:
      - "8001:8000"
    depends_on:
      - chromadb
      - postgres

  retrieval_service:
    container_name: retrieval_service
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - chromadb
      - postgres

  chromadb:
    image: ghcr.io/chroma-db/chroma:latest
    container_name: chromadb
    ports:
      - "8002:8000"
    environment:
      - CHROMADB_SETTING=example

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: document_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
