version: "3.8"

services:
  rag:
    build: .
    container_name: rag-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - chromadb
      - llm

  chromadb:
    image: ghcr.io/chroma-db/chroma:latest
    container_name: chromadb
    ports:
      - "8001:8000"
    environment:
      - CHROMADB_SETTING=example

  llm:
    image: huggingface/transformers-pytorch-cpu
    container_name: llm-service
    volumes:
      - ./models:/models
    environment:
      - MODEL_NAME=mistralai/Mistral-7B-Instruct
    command: ["python", "-m", "transformers.serving", "--model-id", "${MODEL_NAME}", "--device", "cpu"]
    ports:
      - "5000:5000"
