version: "3.8"
services:
  ingestion_service:
    build:
      context: ./ingestion_service
      dockerfile: Dockerfile

  retrieval_service:
    build:
      context: ./retrieval_service
      dockerfile: Dockerfile
